### ISSUE TITLE
No populate samplesdb in venv/bin

### ISSUE THREAD

**Issue by zachcp** [waveform80/samplesdb#1]
I just tried to install you code following the README.txt but after the

 venv/bin/python setup.py develop

there is no file 'populate_samplesdb' in venv/bin and so I cannot install/serve the webapp.

I would like to try your webapp so i am hoping its a quick/easy fix

zach cp

**Comment by waveform80** [comment]
Hi Zach,

Sorry - samplesdb is a long way from ready yet (not even alpha really). Still, if you want to give it a try, do the following:

Set up a venv
Clone the repo
Within the venv:
Run python setup.py develop
Run initialize_samplesdb_db development.ini
Run pserve development.ini --reload
Visit localhost:8080 to see what's done so far!

Obviously development.ini is where various settings are stored - tweak as necessary if you want to use a different port or db engine etc. Let me know what you think!

Cheers,

Dave

**Comment by zachcp** [comment]
Dave,

Thanks for your quick response! I was browsing Github for a sampletracker and saw that yours was the most recently edited. I am not sure if this is what I am looking for but if its simple and gets the job done I am happy to submit bug reports and maybe some code. Following your suggestion above I  get the following error:

Traceback (most recent call last):
  File "venv/bin/initialize_samplesdb_db", line 8, in <module>
    load_entry_point('samplesdb==0.1', 'console_scripts', 'initialize_samplesdb_db')()
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 318, in load_entry_point
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 2221, in load_entry_point
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 1954, in load
  File "/Users/zachpowers/Downloads/samplesdb-master/samplesdb/**init**.py", line 42, in <module>
    from samplesdb.models import DBSession
  File "/Users/zachpowers/Downloads/samplesdb-master/samplesdb/models.py", line 74, in <module>
    from samplesdb.helpers import utcnow
  File "/Users/zachpowers/Downloads/samplesdb-master/samplesdb/helpers.py", line 31, in <module>
    import webhelpers
ImportError: No module named webhelpers

i don't see a webhelpers.py .......

best regards,
zach cp

**Comment by waveform80** [comment]
Damn - I hadn't caught that after removing pyramid_simpleform from the dependencies (I'm now using an internal rewrite of that package, but forgot to copy its dependencies). If you just do "easy_install webhelpers" then "easy_install formencode" inside the venv it should fix it - I'll make sure to include those deps in the next push.

**Comment by zachcp** [comment]
thanks Dave,

I installed the webhelpers and formencode but upon starting the webserver and attempting to create a login I immediately get a login error (posted below).  I tried a few variations on this but got locked out. 

Traceback (most recent call last):
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid_debugtoolbar-1.0.3-py2.7.egg/pyramid_debugtoolbar/panels/performance.py", line 55, in resource_timer_handler
    result = handler(request)
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid-1.3.4-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid_tm-0.5-py2.7.egg/pyramid_tm/**init**.py", line 100, in tm_tween
    response = handler(request)
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid-1.3.4-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid-1.3.4-py2.7.egg/pyramid/config/views.py", line 333, in rendered_view
    result = view(context, request)
  File "/Users/zachpowers/Downloads/samplesdb-master/venv/lib/python2.7/site-packages/pyramid-1.3.4-py2.7.egg/pyramid/config/views.py", line 447, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/Users/zachpowers/Downloads/samplesdb-master/samplesdb/views/account.py", line 185, in create
    owner_role = DBSession.query(Role).filter(Role.id=='owner').one()
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/query.py", line 2184, in one
    ret = list(self)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/query.py", line 2226, in __iter__
    self.session._autoflush()
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/session.py", line 1120, in _autoflush
    self.flush()
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/session.py", line 1718, in flush
    self._flush(objects)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/session.py", line 1789, in _flush
    flush_context.execute()
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/unitofwork.py", line 331, in execute
    rec.execute(self)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/unitofwork.py", line 475, in execute
    uow
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/orm/persistence.py", line 530, in _emit_insert_statements
    execute(statement, multiparams)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/engine/base.py", line 1449, in execute
    params)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "build/bdist.macosx-10.8-intel/egg/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) column email is not unique u'INSERT INTO email_addresses (email, user_id, created, verified) VALUES (?, ?, ?, ?)' (u'zcharlop@rockefeller.edu', 4, '2012-11-20 22:57:07.670666', None)

**Comment by waveform80** [comment]
Ahh - that error means you're attempting to create an address that already exists (I thought I'd made that a slightly friendlier error but apparently that failed! I'll look into it). Anyway, that probably means your first attempt failed because it couldn't find a mail-server (to send the verification code - the settings are in development.ini somewhere near the top).

For now, the simplest way you can test the app is by logging in with the pre-defined administrator account (I've just uploaded the details in a new README but basically it's username "admin@example.com" with password "adminpass").

If you want to force your ID to be verified you can fire up the pyramid shell from within the venv with:

$ pshell development.ini

Inside that, the following should force-verify your ID (but this is off the top of my head, so I might get the odd thing wrong!):

from samplesdb.models import *
from datetime import datetime
import transaction
EmailAddress.by_email('zcharlop@rockefeller.edu').verified = datetime.utcnow()
transaction.commit()

Then hit Ctrl+D to exit pshell and re-run pserve. Eventually there should be user interface for the administrator to do this, but at the moment I'm concentrating on finishing the collections and sample interfaces before I get onto the admin stuff (on the basis I can pretty easily manually hack anything I need into the database for dev / testing purposes).

Anyway, bed time for me - have fun!

Dave.
